### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by whitegolum** [Aeolic/CultistMod#3]

**Comment by Aeolic** [comment]
It's at the bottom of the readme :) Maybe I should put it at the top, it's Aeolic#5560

**Comment by NotHunter101** [comment]
Do not make any mods for this person. They have contacted me in the past and attempted to get me to merge other people's mods together without the consent of the original creators, and also attempted to scam me into doing it with a false promise of payment.

**Comment by whitegolum** [comment]
@NotHunter101  D: how rude I was telling him to work with u and make both mods compatiable tog , not cool from u :(
